# Generated by Django 6.1 on 2026-08-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('process', 'IN PROCESS'), ('deliver', 'DELIVERED'), ('fail', 'DELIVERY FAILED')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=25)),
                ('url', models.URLField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('create', 'Created'), ('delete', 'Deleted'), ('update', 'Updated')], max_length=10)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('attempt_number', models.IntegerField()),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('attempt_status', models.CharField(choices=[('SU', 'Success'), ('CE', 'Failed - Client Error'), ('SE', 'Failed - Server Error'), ('TO', 'Failed - Timeout'), ('COE', 'Failed - Connection Error')], max_length=5)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='webhook.delivery')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.endpoint'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webhook.event'),
        ),
    ]
