# Generated by Django 6.1 on 2026-09-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0003_processedidempotentkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='secret',
            field=models.CharField(default='5a4243f1089271f2ade73b6efdf9ac8b3e12e3c26af5971e961e68baf2a6ffad'),
        ),
    ]
