# Generated by Django 6.1 on 2026-09-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook', '0004_endpoint_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='circuit_broken_until',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='consecutive_failures',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='secret',
            field=models.CharField(default='c625de18dafbaf61cc3b7d0a20b2021631a8cdf1cfa0f09ee1df2ea6f042dd44'),
        ),
    ]
